use_frameworks!

platform :ios, '9.0'

target 'BlueIntentControllerTransitioning_Example' do
  pod 'BlueIntentControllerTransitioning', :path => '../'

  target 'BlueIntentControllerTransitioning_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
