# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage
# * https://docs.travis-ci.com/user/languages/objective-c/

osx_image: xcode12.4
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install --project-directory=Example
script:
  # - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/BlueIntentControllerTransitioning.xcworkspace -scheme BlueIntentControllerTransitioning-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
# deploy:
# - provider: pages
#   local-dir: docs
#   github-token: $Travis_Token
#   skip-cleanup: true
#   keep-history: true
